# Generated by Django 5.2.5 on 2025-08-14 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shift_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('past_week_hours', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.PositiveIntegerField(unique=True)),
                ('distance_km', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('traffic_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('base_time_min', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_num_drivers', models.PositiveIntegerField()),
                ('input_start_time', models.TimeField()),
                ('input_max_hours', models.PositiveIntegerField()),
                ('total_profit', models.IntegerField()),
                ('efficiency_score', models.FloatField()),
                ('on_time', models.IntegerField()),
                ('late', models.IntegerField()),
                ('fuel_cost_total', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('value_rs', models.PositiveIntegerField()),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.route')),
            ],
        ),
    ]
